version: '3'

volumes:
  postgres_volume:

services:
  app:
    env_file:
      - ../what-to-watch-golang/.env
    build:
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
      - "8098:8098"
    depends_on:
      - db
    restart: on-failure


  db:
    image: postgres:14-alpine3.20
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  app-migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    restart: on-failure